FROM rasa/rasa:3.6.0
WORKDIR /app
COPY . /app

EXPOSE 8080

ENTRYPOINT []

CMD ["/bin/bash","-lc","rasa run --enable-api -i 0.0.0.0 -p ${PORT:-8080} --cors \"${CORS_ORIGINS:-*}\" --endpoints endpoints.yml"]
