FROM rasa/rasa-sdk:3.6.2
USER root
WORKDIR /app
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir -r /app/requirements.txt
COPY actions/ /app/actions
# Khuyến nghị: dùng port mặc định 5055 để khỏi lệch endpoints.yml
EXPOSE 8080
USER 1001
CMD ["start", "--actions", "actions", "--port", "5055"]
