FROM rasa/rasa:3.6.0
WORKDIR /app
COPY . /app

EXPOSE 8080
ENTRYPOINT []

# Rasa sẽ tự chọn file .tar.gz mới nhất trong /app/models
CMD ["/bin/bash","-lc","rasa run --enable-api --credentials credentials.yml --endpoints endpoints.yml --model models -i 0.0.0.0 -p ${PORT:-8080} --cors \"${CORS_ORIGINS:-*}\""]
